// Mock data + handlers for the Fanju AI SEO Lab admin UI.
// Used when LAB_API_BASE env var is not set, so the dashboard works
// out of the box for demos without the Cloudflare Worker / D1 / Modal.

import type {
  LabArticle,
  LabPlatformAccount,
  LabPublishJob,
  LabSeoCheck,
  LabStats,
} from "@/lib/lab/types"

const NOW = () => new Date().toISOString()
const ago = (mins: number) => new Date(Date.now() - mins * 60_000).toISOString()

export const mockArticles: LabArticle[] = [
  {
    id: "art_001",
    title: "深圳社交聚餐：陌生人饭局如何破冰",
    slug: "shenzhen-social-dining-icebreaker",
    lang: "zh",
    topic: "深圳社交聚餐",
    github_path: "content/articles/2026/05/art_001.md",
    status: "published",
    seo_score: 88,
    seo_report_r2: null,
    cover_r2: null,
    created_at: ago(60 * 24),
    updated_at: ago(60 * 2),
  },
  {
    id: "art_002",
    title: "上海周末饭局推荐 Top 10",
    slug: "shanghai-weekend-dinner-top10",
    lang: "zh",
    topic: "上海周末饭局",
    github_path: "content/articles/2026/05/art_002.md",
    status: "ready",
    seo_score: 74,
    seo_report_r2: null,
    cover_r2: null,
    created_at: ago(180),
    updated_at: ago(40),
  },
  {
    id: "art_003",
    title: "How To Meet New Friends Over Dinner In SF",
    slug: "sf-meet-friends-over-dinner",
    lang: "en",
    topic: "SF social dining",
    github_path: "content/articles/2026/05/art_003.md",
    status: "draft",
    seo_score: 52,
    seo_report_r2: null,
    cover_r2: null,
    created_at: ago(20),
    updated_at: ago(10),
  },
]

export const mockJobs: LabPublishJob[] = [
  {
    id: "job_001",
    article_id: "art_001",
    article_slug: "shenzhen-social-dining-icebreaker",
    platform: "zhihu",
    status: "success",
    rewrite_github_path: "content/rewrites/art_001/zhihu.md",
    published_url: "https://zhuanlan.zhihu.com/p/123456",
    error_msg: null,
    error_dump_r2: null,
    attempt_count: 1,
    scheduled_at: ago(120),
    started_at: ago(118),
    finished_at: ago(116),
    created_at: ago(120),
  },
  {
    id: "job_002",
    article_id: "art_001",
    article_slug: "shenzhen-social-dining-icebreaker",
    platform: "csdn",
    status: "success",
    rewrite_github_path: "content/rewrites/art_001/csdn.md",
    published_url: "https://blog.csdn.net/fanju/article/details/1",
    error_msg: null,
    error_dump_r2: null,
    attempt_count: 1,
    scheduled_at: ago(115),
    started_at: ago(113),
    finished_at: ago(111),
    created_at: ago(115),
  },
  {
    id: "job_003",
    article_id: "art_002",
    article_slug: "shanghai-weekend-dinner-top10",
    platform: "juejin",
    status: "running",
    rewrite_github_path: "content/rewrites/art_002/juejin.md",
    published_url: null,
    error_msg: null,
    error_dump_r2: null,
    attempt_count: 1,
    scheduled_at: ago(5),
    started_at: ago(2),
    finished_at: null,
    created_at: ago(5),
  },
  {
    id: "job_004",
    article_id: "art_002",
    article_slug: "shanghai-weekend-dinner-top10",
    platform: "xiaohongshu",
    status: "pending",
    rewrite_github_path: null,
    published_url: null,
    error_msg: null,
    error_dump_r2: null,
    attempt_count: 0,
    scheduled_at: ago(1),
    started_at: null,
    finished_at: null,
    created_at: ago(1),
  },
  {
    id: "job_005",
    article_id: "art_001",
    article_slug: "shenzhen-social-dining-icebreaker",
    platform: "weibo",
    status: "failed",
    rewrite_github_path: "content/rewrites/art_001/weibo.md",
    published_url: null,
    error_msg: "captcha solver timeout after 3 attempts",
    error_dump_r2: "errors/job_005.html",
    attempt_count: 3,
    scheduled_at: ago(200),
    started_at: ago(198),
    finished_at: ago(180),
    created_at: ago(200),
  },
]

const PLATFORM_DEFS: Array<{ platform: string; display_name: string; daily_limit: number }> = [
  { platform: "zhihu", display_name: "知乎", daily_limit: 3 },
  { platform: "csdn", display_name: "CSDN", daily_limit: 5 },
  { platform: "juejin", display_name: "掘金", daily_limit: 5 },
  { platform: "jianshu", display_name: "简书", daily_limit: 3 },
  { platform: "weibo", display_name: "微博", daily_limit: 5 },
  { platform: "xiaohongshu", display_name: "小红书", daily_limit: 3 },
  { platform: "douban", display_name: "豆瓣", daily_limit: 2 },
  { platform: "toutiao", display_name: "今日头条", daily_limit: 3 },
  { platform: "baijiahao", display_name: "百家号", daily_limit: 3 },
  { platform: "bilibili", display_name: "B站专栏", daily_limit: 2 },
  { platform: "devto", display_name: "DEV.to", daily_limit: 5 },
  { platform: "hashnode", display_name: "Hashnode", daily_limit: 5 },
  { platform: "medium", display_name: "Medium", daily_limit: 3 },
  { platform: "bluesky", display_name: "Bluesky", daily_limit: 10 },
  { platform: "reddit", display_name: "Reddit", daily_limit: 3 },
]

export const mockPlatforms: LabPlatformAccount[] = PLATFORM_DEFS.map((p, i) => ({
  platform: p.platform,
  display_name: p.display_name,
  is_active: i % 7 === 6 ? 0 : 1,
  daily_limit: p.daily_limit,
  published_today: Math.min(p.daily_limit, Math.floor(Math.random() * (p.daily_limit + 1))),
  last_reset_date: NOW().slice(0, 10),
  session_valid: i % 5 === 4 ? 0 : 1,
  last_check_at: ago(30 + i * 5),
  notes: null,
}))

export const mockSeoChecks: LabSeoCheck[] = [
  {
    id: "seo_001",
    article_id: "art_001",
    slug: "shenzhen-social-dining-icebreaker",
    title: "深圳社交聚餐：陌生人饭局如何破冰",
    checked_at: ago(60),
    score: 88,
    issues: "missing meta description; H2 density slightly low",
    report_r2: null,
    verdict: "good",
  },
  {
    id: "seo_002",
    article_id: "art_002",
    slug: "shanghai-weekend-dinner-top10",
    title: "上海周末饭局推荐 Top 10",
    checked_at: ago(40),
    score: 74,
    issues: "keyword 'shanghai dinner' under-used; image alt text missing on 3 images",
    report_r2: null,
    verdict: "ok",
  },
  {
    id: "seo_003",
    article_id: "art_003",
    slug: "sf-meet-friends-over-dinner",
    title: "How To Meet New Friends Over Dinner In SF",
    checked_at: ago(15),
    score: 52,
    issues: "title too generic; no internal links; meta description over 160 chars",
    report_r2: null,
    verdict: "needs-work",
  },
]

export const mockStats: LabStats = {
  articles: [
    { status: "draft", count: 1 },
    { status: "ready", count: 1 },
    { status: "published", count: 1 },
    { status: "failed", count: 0 },
  ],
  jobs: [
    { status: "pending", count: 1 },
    { status: "running", count: 1 },
    { status: "success", count: 2 },
    { status: "failed", count: 1 },
    { status: "skipped", count: 0 },
  ],
  platforms: mockPlatforms.map((p) => ({
    platform: p.platform,
    published_today: p.published_today,
    daily_limit: p.daily_limit,
    is_active: p.is_active,
    session_valid: p.session_valid,
  })),
}
